<li>
				<a class="p_l bg_blue" href="/bk/al/" target="_blank">{dede:field name='typename'/}</a>
				<div class="p_r">
					<a class="tit " href="/bk/al/13590.html" target="_blank" title="耶鲁大学录取捷报：不以分数论能力">耶鲁大学录取捷报：不以分数</a>
					<p>虽然学生的标准化成绩一般，但是在申请过程中，通过啄木鸟顾问的指导，学生合理挖掘课外活动、书写申请文书，最终取得满意的结果!</p>
				</div>
				<div class="clear"></div>
				<p class="p_b">
				标签：
<a href= target="_blank">结论</a><a href= target="_blank">美国大学EA申请</a><a href= target="_blank">武大</a>
				</p>
			</li>