<li><a href="/toefl/toeflzixun/21465.html" target="_blank" title="2016年TOP100美国大学本科申请托福要求汇总">2016年TOP100美国大学本科申请托</a></li>



				</ul>
			</div>
			<div class="type_floors_left_box bt_blue">
				<a class="type_floors_left_box_tit tit_blue" href="/bk/al/" target="_blank">成功案例</a>
				<ul class="type_floors_left_box_list">
<li><a href="/bk/al/13590.html" target="_blank" title="耶鲁大学录取捷报：不以分数论能力">耶鲁：不以分数论能力</a></li>
<li><a href="/bk/al/499.html" target="_blank" title="同时被西北大学、密歇根大学、霍山学院、北卡">同时被西北大学、密歇根大</a></li>
<li><a href="/bk/al/19280.html" target="_blank" title="穹顶之下，分析雾霾学生被哥大等6所名校录取！">分析雾霾学生被哥大录取</a></li>
<li><a href="/bk/al/19291.html" target="_blank" title=""中华好学生"冲刺美国前10名校，成功背后的亮点在哪儿？">中华好学生冲刺前10名校</a></li>
<li><a href="/plus/view.php?aid=20369" target="_blank" title="2015美国本科申请捷报 全奖录取">2015美国本科申请捷报 全奖</a></li>
<li><a href="/plus/view.php?aid=20370" target="_blank" title="2015美国研究生申请捷报 top50">2015美国研究生申请捷报 t</a></li>

				</ul>
			</div>
			<div class="clear"></div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<div class="border_box bt_none" style="height:99%;">
					<div class="type_right_box_tit">
						<span class="cl_blue tabs4">美国本科留学服务</span>
						<div class="clear"></div>
					</div>
					<ul class="type_floors_left_box_list">

							<li><a href="/zhuanti/iplanning/" target="_blank">精英计划</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/zhuanti/guihua/" target="_blank">学习规划</a></li>
							<li><a href="/zhuanti/huodong/" target="_blank">前10/30/50名校个性活动策划</a></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">托福全日制保分封闭训练营</a><br /></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">SAT全日制保分封闭训练营</a><br />
					  </li>
							<li><a href="/zhuanti/zhongkeyuan2015/" target="_blank">中科院科研实习项目</a></li></ul>
				</div>
			</div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/bk/msfx/" target="_blank">名师经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/bk/msfx/21382.html" target="_blank" title="哈佛！哈佛？"><strong>哈佛！哈佛？</strong></a></li>
<li><a href="/bk/msfx/21344.html" target="_blank" title="在申请季为自己写一封情书">在申请季为自己写一封情书</a></li>
<li><a href="/bk/msfx/21343.html" target="_blank" title="你们所不知道的宾夕法尼亚州立大学">你们所不知道的宾夕法尼亚州</a></li>
<li><a href="/bk/msfx/21246.html" target="_blank" title="SAT风波过后，撰文安慰一下自己"><strong>SAT风波过后，撰文安慰一下</strong></a></li>
<li><a href="/bk/msfx/10803.html" target="_blank" title="李开复：留学给我的十个礼物">李开复：留学给我的十个礼</a></li>
<li><a href="/bk/msfx/12601.html" target="_blank" title="啄木鸟教育老师：梦想永远是现在式">啄木鸟教育老师：梦想永远</a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/bk/xyfx/" target="_blank">学生经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/bk/xyfx/21392.html" target="_blank" title="响彻斯坦福演讲：你生来就是要体验疯狂的"><strong>响彻斯坦福演讲：你生来就</strong></a></li>
<li><a href="/bk/xyfx/13475.html" target="_blank" title="【海外生活】如何尽快适应校园生活">【海外生活】如何尽快适应</a></li>
<li><a href="/bk/xyfx/3939.html" target="_blank" title="美国留学理财须知">美国留学理财须知</a></li>
<li><a href="/bk/xyfx/3953.html" target="_blank" title="美今年机票价格恐疯狂上涨">美今年机票价格恐疯狂上涨</a></li>
<li><a href="/bk/xyfx/3964.html" target="_blank" title="留学美国：如何办理回国证明？">留学美国：如何办理回国证</a></li>
<li><a href="/bk/xyfx/3965.html" target="_blank" title="赴美国留学旅游逾期停留后果严重">赴美国留学旅游逾期停留后</a></li>

				</ul>
			</div>
			<div class="type_floors_left_adbox mt10">
				<ul>
					<li style="display:inline;float:left;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103026");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103027");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103028");</script></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
<!--type_floors01_right-->
		<div class="type_floors_right">
			<div class="type_floors_right_first bt_blue">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/school/university/" target="_blank">大学排行</a><a class="tabs_more" href="/school/university/" target="_blank">更多</a>
					</div>
				  <div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/school/university/St-Michael's-College.html" target="_blank" title="圣迈克尔学院/St.Michael's College">圣迈克尔学院/St.Michael's Col</a></li>
<li><a href="/school/university/Cornell-College.html" target="_blank" title="康奈尔学院/Cornell College">康奈尔学院/Cornell College</a></li>
<li><a href="/school/university/Saint-Mary's-College.html" target="_blank" title="圣玛丽学院/Saint Mary's College">圣玛丽学院/Saint Mary's Colleg</a></li>
<li><a href="/school/university/Berea-College.html" target="_blank" title="伯利亚学院/Berea College">伯利亚学院/Berea College</a></li>
<li><a href="/school/university/Soka-University-of-America.html" target="_blank" title="美国创价大学/Soka University of America">美国创价大学/Soka University </a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_first bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/bk/zhinan/" target="_blank">留学指南</a><a class="tabs_more" href="/bk/zhinan/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/bk/zhinan/21244.html" target="_blank" title="2016年各门AP考试时间表"><strong>2016年各门AP考试时间表</strong></a></li>
<li><a href="/bk/zhinan/21105.html" target="_blank" title="美国留学招生官认可的十类课外活动">美国留学招生官认可的十类课外活动</a></li>
<li><a href="/bk/zhinan/20980.html" target="_blank" title="美国留学本科申请材料清单">美国留学本科申请材料清单</a></li>
<li><a href="/bk/zhinan/20979.html" target="_blank" title="美国留学本科五种留学方式">美国留学本科五种留学方式</a></li>
<li><a href="/bk/zhinan/20969.html" target="_blank" title="去美国留学如何选择学校">去美国留学如何选择学校</a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_second bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" >托福资料下载</a><a class="tabs_more" href="/toefl/toeflziliao/" target="_blank">更多</a>
					</div>
						<ul class="type_right_box_list">
	<li><a href="/toefl/toeflziliao/16759.html" target="_blank" title="浅谈托福口语学习">浅谈托福口语学习</a></li>
<li><a href="/toefl/toeflziliao/16571.html" target="_blank" title="如何正确使用托福机经？">如何正确使用托福机经？</a></li>
<li><a href="/toefl/toeflziliao/16570.html" target="_blank" title="托福听力怎样拿高分？">托福听力怎样拿高分？</a></li>
<li><a href="/toefl/toeflziliao/16569.html" target="_blank" title="托福阅读为何必须要拿高分？">托福阅读为何必须要拿高分？</a></li>

						</ul>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
<!--type_floors02 - 研究生-->
	<div class="type_floors">
		<div class="type_floors_head">
			<div class="type_floors_head_tit a27_box"><span class="f_ico">2F</span><a class="f_tit" href="/yjs/" target="_blank">美国研究生留学申请</a></div>
			<div class="type_floors_head_tabs">
				<a href="/lxzt/lxsq/" target="_blank">研究生专题</a><a  class="a_kefu" target="_blank">在线咨询</a><a href="/pinggu/" target="_blank">留学评估</a>
			</div>	
		</div>
<!--type_floors02_left-->
		<div class="type_floors_left">
			<div class="type_floors_left_box mr10 type_floors_left_bannerbox">
				<script type="text/javascript">BAIDU_CLB_fillSlot("1103029");</script>
			</div>
			<div class="type_floors_left_box bt_blue mr10">
				<a class="type_floors_left_box_tit tit_blue" href="/yjs/zx/" target="_blank">资讯动态</a>
				<ul class="type_floors_left_box_list">
<li><a href="/toefl/toeflzixun/21466.html" target="_blank" title="2016年TOP100美国大学研究生申请托福要求汇总">2016年TOP100美国大学研究生申请</a></li>
<li><a href="/yjs/zx/21461.html" target="_blank" title="芝加哥大学为什么这样要求自己的学生？"><strong>芝加哥大学为什么这样要求</strong></a></li>
<li><a href="/yjs/zx/21434.html" target="_blank" title="如何轻松愉快的提高GRE/GAMT成绩"><strong>如何轻松愉快的提高GRE/GA</strong></a></li>
<li><a href="/yjs/zx/21436.html" target="_blank" title="你是怎样的人，就会在选择怎样的美国城市"><strong>你是怎样的人，就会在选择</strong></a></li>
<li><a href="/yjs/zx/21399.html" target="_blank" title="真实的美国留学生活：痛并快乐着！"><strong>真实的美国留学生活：痛并</strong></a></li>
<li><a href="/yjs/zx/21400.html" target="_blank" title="名校不是事儿：美帝人民咋看"哈佛"？"><strong>名校不是事儿：美帝人民咋</strong></a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue">
				<a class="type_floors_left_box_tit tit_blue" href="/yjs/al/" target="_blank">成功案例</a>
				<ul class="type_floors_left_box_list">
<li><a href="/yjs/al/21324.html" target="_blank" title="剑走偏锋 GPA1.889学生成功逆袭转学到奥本！"><strong>剑走偏锋 GPA1.889学生成功逆</strong></a></li>
<li><a href="/plus/view.php?aid=1867" target="_blank" title="啄木鸟教育2010年美国名校研究生及本科转学申请">2010年美国名校研究生录取</a></li>
<li><a href="/yjs/al/21216.html" target="_blank" title="理工科的规划案例">理工科的规划案例</a></li>
<li><a href="/yjs/al/21217.html" target="_blank" title="文科的规划案例">文科的规划案例</a></li>
<li><a href="/yjs/al/18866.html" target="_blank" title="啄木鸟美国研究生录取捷报1">啄木鸟美国研究生录取捷报</a></li>
<li><a href="/yjs/al/18868.html" target="_blank" title="啄木鸟美国研究生录取捷报3">啄木鸟美国研究生录取捷报</a></li>

				</ul>
			</div>
			<div class="clear"></div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<div class="border_box bt_none" style="height:99%;">
					<div class="type_right_box_tit">
						<span class="cl_blue tabs4">美国研究生留学服务</span>
						<div class="clear"></div>
					</div>
					<ul class="type_floors_left_box_list">
<li><a href="/zhuanti/jiebao_yjs2015/" target="_blank">2015美国研究生录取捷报</a></li><li><a href="/zhuanti/zhongkeyuan2015/" target="_blank">跟随中科院教授-参与科研实习项目</a></li>
							
							<li><a href="/zhuanti/yjs_1pic/" target="_blank">读懂2015美国研究生留学申请</a><br />
</li>
							
							<li><a href="/zhuanti/20150505zuanshidaoshi_yjs/" target="_blank">研究生钻石导师通道-1对1规划指导</a></li>
                            <li><a href="/zhuanti/shuangdaoshi_yjs/" target="_blank">研究生申请双金导师开启名校大门</a></li>
				  </ul>
				</div>
			</div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/yjs/msfx/" target="_blank">名师经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/yjs/msfx/21309.html" target="_blank" title="统计女孩跨专业实现计算机博士梦"><strong>统计女孩跨专业实现计算机</strong></a></li>
<li><a href="/yjs/msfx/13950.html" target="_blank" title="刘瑜：哈佛这样的牛校牛在哪">刘瑜：哈佛这样的牛校牛在</a></li>
<li><a href="/yjs/msfx/14373.html" target="_blank" title="在耶鲁，一门触及内心的写作课">在耶鲁，一门触及内心的写</a></li>
<li><a href="/yjs/msfx/14956.html" target="_blank" title="美国大学75条黄金法则让你脱颖而出">美国大学75条黄金法则让你</a></li>
<li><a href="/yjs/msfx/18370.html" target="_blank" title="美国留学马里兰大学帕克分校专业介绍">美国留学马里兰大学帕克分</a></li>
<li><a href="/yjs/msfx/18329.html" target="_blank" title="美国留学乔治华盛顿大学咨询心理学专业介绍">美国留学乔治华盛顿大学咨</a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/yjs/xyfx/" target="_blank">学员经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/yjs/xyfx/3122.html" target="_blank" title="出国留学贷款条件是什么样的">出国留学贷款条件是什么样</a></li>
<li><a href="/yjs/xyfx/3121.html" target="_blank" title="留学美国注意事项之行前和就医">留学美国注意事项之行前和</a></li>
<li><a href="/yjs/xyfx/3221.html" target="_blank" title="美国留学贷款为签证排忧">美国留学贷款为签证排忧</a></li>
<li><a href="/yjs/xyfx/3384.html" target="_blank" title="美国留学行前准备及入境程序">美国留学行前准备及入境程</a></li>
<li><a href="/yjs/xyfx/3396.html" target="_blank" title="从麻省理工学院MIT评出的2010年"TR35"看中美教育差异">从麻省理工学院MIT评出的</a></li>
<li><a href="/yjs/xyfx/3405.html" target="_blank" title="出国留学应注意的八大事项">出国留学应注意的八大事项</a></li>

				</ul>
			</div>
			<div class="type_floors_left_adbox mt10">
				<ul>
					<li style="display:inline;float:left;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103030");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103031");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103032");</script></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
<!--type_floors02_right-->
		<div class="type_floors_right">
			<div class="type_floors_right_first bt_blue">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/school/university/" target="_blank">大学排行</a><a class="tabs_more" href="/school/university/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/school/university/St-Michael's-College.html" target="_blank" title="圣迈克尔学院/St.Michael's College">圣迈克尔学院/St.Michael's Col</a></li>
<li><a href="/school/university/Cornell-College.html" target="_blank" title="康奈尔学院/Cornell College">康奈尔学院/Cornell College</a></li>
<li><a href="/school/university/Saint-Mary's-College.html" target="_blank" title="圣玛丽学院/Saint Mary's College">圣玛丽学院/Saint Mary's Colleg</a></li>
<li><a href="/school/university/Berea-College.html" target="_blank" title="伯利亚学院/Berea College">伯利亚学院/Berea College</a></li>
<li><a href="/school/university/Soka-University-of-America.html" target="_blank" title="美国创价大学/Soka University of America">美国创价大学/Soka University </a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_first bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/yjs/zhinan/" target="_blank">留学指南</a><a class="tabs_more" href="/yjs/zhinan/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/yjs/zhinan/21460.html" target="_blank" title="美国研究生网申申请时间你知道吗？"><strong>美国研究生网申申请时间你知</strong></a></li>
<li><a href="/yjs/zhinan/21462.html" target="_blank" title="美国大学里那些奇葩专业，不怕众叛亲离才敢学"><strong>美国大学里那些奇葩专业，不</strong></a></li>
<li><a href="/yjs/zhinan/21435.html" target="_blank" title="美国研究生留学申请流程解读"><strong>美国研究生留学申请流程解读</strong></a></li>
<li><a href="/yjs/zx/21393.html" target="_blank" title="解读美国研究生留学申请三大注意事项">美国研究生留学申请三大事项</a></li>
<li><a href="/yjs/zhinan/21349.html" target="_blank" title="DIY申请美国研究生不可不知的30个基本常识"><strong>DIY申请美国研究生不可不知的</strong></a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_second bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/sat/SATziliao/" target="_blank">SAT资料下载</a><a class="tabs_more" href="/sat/SATziliao/" target="_blank">更多</a>
					</div>
						<ul class="type_right_box_list">
	<li><a href="/sat/SATziliao/12715.html" target="_blank" title="SAT备考资料重要性排名"><strong>SAT备考资料重要性排名</strong></a></li>
<li><a href="/sat/SATziliao/12773.html" target="_blank" title="sat历年真题下载">sat真题</a></li>
<li><a href="/sat/SATziliao/12775.html" target="_blank" title="[sat词汇]猴哥SAT词频8000大礼包">[sat词汇]猴哥SAT词频8000大礼包</a></li>
<li><a href="/sat/SATziliao/12800.html" target="_blank" title="猴哥：SAT满分备考三部曲">猴哥：SAT满分备考三部曲</a></li>

						</ul>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>

<!--type_floors03 - SSAT-->
	<div class="type_floors">
		<div class="type_floors_head">
			<div class="type_floors_head_tit a27_box"><span class="f_ico">3F</span><a class="f_tit" href="/gz/" target="_blank">美国高中留学申请</a></div>
			<div class="type_floors_head_tabs">
				<a href="/lxzt/lxsq/" target="_blank">高中专题</a><a class="a_kefu" target="_blank">在线咨询</a><a href="/pinggu/" target="_blank">留学评估</a>
			</div>	
		</div>
<!--type_floors03_left-->
		<div class="type_floors_left">
			<div class="type_floors_left_box mr10 type_floors_left_bannerbox">
				<script type="text/javascript">BAIDU_CLB_fillSlot("1103033");</script>
			</div>
			<div class="type_floors_left_box bt_blue mr10">
				<a class="type_floors_left_box_tit tit_blue" href="/gz/zx/" target="_blank">资讯动态</a>
				<ul class="type_floors_left_box_list">
<li><a href="/gz/zx/21477.html" target="_blank" title="美国低龄留学申请未来两年将进入白热化">美国低龄留学申请未来两年将</a></li>
<li><a href="/gz/zx/21459.html" target="_blank" title="安多福招生官：顶尖美高最看重学生哪些特质？"><strong>安多福招生官：顶尖美高最</strong></a></li>
<li><a href="/gz/zx/21429.html" target="_blank" title="美高面试需要注意哪些问题？"><strong>美高面试需要注意哪些问题</strong></a></li>
<li><a href="/gz/zx/21433.html" target="_blank" title="美高申请保底学校不保底怎么办"><strong>美高申请保底学校不保底怎</strong></a></li>
<li><a href="/gz/zx/21397.html" target="_blank" title="斯坦福教授：父母如何帮孩子找到目标和动力？"><strong>斯坦福教授：父母如何帮孩</strong></a></li>
<li><a href="/gz/zx/21346.html" target="_blank" title="2016美国高中选校&amp;面试指导会"><strong>2016美国高中选校&amp;面试指</strong></a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue">
				<a class="type_floors_left_box_tit tit_blue" href="/gz/al/" target="_blank">成功案例</a>
				<ul class="type_floors_left_box_list">
<li><a href="/gz/al/21115.html" target="_blank" title="2014年啄木鸟教育高中录取案例">2014年啄木鸟教育高中录取案例</a></li>
<li><a href="/gz/al/21116.html" target="_blank" title="2015年啄木鸟教育高中录取案例">2015啄木鸟教育高中录取案例</a></li>
<li><a href="/gz/al/20050.html" target="_blank" title="勇于挑战，平凡有你">勇于挑战，平凡有你</a></li>
<li><a href="/gz/al/20051.html" target="_blank" title="低分神话，活动致胜">低分神话，活动致胜</a></li>
<li><a href="/gz/al/20041.html" target="_blank" title="蜕变让我完成跳级">蜕变让我完成跳级</a></li>
<li><a href="/gz/al/20042.html" target="_blank" title="早规划稳录取">早规划稳录取</a></li>

				</ul>
			</div>
			<div class="clear"></div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<div class="border_box bt_none" style="height:99%;">
					<div class="type_right_box_tit">
						<span class="cl_blue tabs4">美国高中留学服务</span>
						<div class="clear"></div>
					</div>
					<ul class="type_floors_left_box_list">
							<li><a href="/zhuanti/iplanning/" target="_blank">精英计划</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/zhuanti/guihua/" target="_blank">学习规划</a></li>
							<li><a href="/zhuanti/iplanning/" target="_blank">初高中生签约保录美国前30/50名校</a></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">托福全日制保分封闭训练营</a><br /></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">SAT全日制保分封闭训练营</a><br /></li>
							<li><a href="/zhuanti/pzmj/" target="_blank">高二/三学生冲刺美国前50名校</a></li>
				  </ul>
				</div>
			</div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/gz/msfx/" target="_blank">名师经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/gz/msfx/18394.html" target="_blank" title="美国留学东部的优秀高中介绍">美国留学东部的优秀高中介</a></li>
<li><a href="/gz/msfx/18415.html" target="_blank" title="美国高中留学面试需注意的细节介绍">美国高中留学面试需注意的</a></li>
<li><a href="/gz/msfx/15259.html" target="_blank" title="美国高中留学生应对异国文化差异的方法">美国高中留学生应对异国文</a></li>
<li><a href="/gz/msfx/15351.html" target="_blank" title="浅谈美国高中留学中私立高中的选择攻略">浅谈美国高中留学中私立高</a></li>
<li><a href="/gz/msfx/15997.html" target="_blank" title="揭秘美国高中留学的五大关键因素">揭秘美国高中留学的五大关</a></li>
<li><a href="/gz/msfx/16045.html" target="_blank" title="美国高中留学简历与推荐信不容忽视">美国高中留学简历与推荐信</a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/gz/xyfx/" target="_blank">学员经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/gz/xyfx/21327.html" target="_blank" title="人大院长9岁儿子送进美国小学，感觉挨了一闷棍"><strong>人大院长9岁儿子送进美国小</strong></a></li>
<li><a href="/gz/xyfx/21325.html" target="_blank" title="辗转中国、新加坡、北美三地的择校经历总结"><strong>辗转中国、新加坡、北美三</strong></a></li>
<li><a href="/gz/xyfx/21242.html" target="_blank" title="分享两个儿子如何申请到Phillips Academy Andover"><strong>分享两个儿子如何申请到</strong></a></li>
<li><a href="/gz/xyfx/13481.html" target="_blank" title="美国高中留学 中国留学生人数4年增5倍">美国高中留学 中国留学生人</a></li>
<li><a href="/gz/xyfx/15296.html" target="_blank" title="留学生分享：如何学英语有效？">留学生分享：如何学英语有</a></li>
<li><a href="/gz/xyfx/15371.html" target="_blank" title="留学生找工作辛酸史：专业扎堆供过于求">留学生找工作辛酸史：专业</a></li>

				</ul>
			</div>
			<div class="type_floors_left_adbox mt10">
				<ul>
					<li style="display:inline;float:left;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103034");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103035");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103036");</script></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
<!--type_floors03_right-->
		<div class="type_floors_right">
			<div class="type_floors_right_first bt_blue">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/school/high/" target="_blank">高中排行</a><a class="tabs_more" href="/school/high/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/school/high/21458.html" target="_blank" title="格罗顿高中">Groton School</a></li>
<li><a href="/school/high/21457.html" target="_blank" title="啄木鸟教育访美高记：佩迪学校"><strong>啄木鸟教育访美高记：佩迪学</strong></a></li>
<li><a href="/school/high/21432.html" target="_blank" title="圣保罗高中">St. Paul's School</a></li>
<li><a href="/yxk/gzyxk/2015/1120/21396.html" target="_blank" title="菲利普斯埃克赛特学院">Phillips Exeter Academy</a></li>
<li><a href="/yxk/gzyxk/2015/1119/21381.html" target="_blank" title="菲利普斯安多佛学院">Phillips Academy Andover</a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_first bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/gz/zhinan/" target="_blank">留学指南</a><a class="tabs_more" href="/gz/zhinan/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/gz/zhinan/21086.html" target="_blank" title="去美国读高中家长担心的四大问题">去美国读高中家长担心的四大</a></li>
<li><a href="/gz/zhinan/21359.html" target="_blank" title="自由选择的困惑——美国高中选课攻略"><strong>自由选择的困惑&mdash;&mdash;美国高中</strong></a></li>
<li><a href="/gz/zhinan/21347.html" target="_blank" title="【上最好的高中】申请面试篇"><strong>【上最好的高中】申请面试篇</strong></a></li>
<li><a href="/gz/zhinan/21348.html" target="_blank" title="【上最好的高中】面试问题汇总"><strong>【上最好的高中】面试问题汇</strong></a></li>
<li><a href="/gz/zhinan/21262.html" target="_blank" title="2015年11月-12月美国高中面试时间表"><strong>2015年11月-12月美国高中面试时</strong></a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_second bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/ssat/SSATziliao/" target="_blank">SSAT资料下载</a><a class="tabs_more" href="/ssat/SSATziliao/" target="_blank">更多</a>
					</div>
						<ul class="type_right_box_list">
	<li><a href="/ssat/SSATziliao/20064.html" target="_blank" title="猴哥SSAT同义类比五步训练法">猴哥SSAT同义类比五步训练法</a></li>
<li><a href="/ssat/SSATziliao/20065.html" target="_blank" title="猴哥SSAT四步训练法">猴哥SSAT四步训练法</a></li>
<li><a href="/ssat/SSATziliao/20066.html" target="_blank" title="猴哥SSAT写作五步训练法">猴哥SSAT写作五步训练法</a></li>
<li><a href="/ssat/SSATziliao/20067.html" target="_blank" title="SSAT数学备考方法">SSAT数学备考方法</a></li>

						</ul>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	
<!--type_floors04 - 转学-->
	<div class="type_floors">
		<div class="type_floors_head">
			<div class="type_floors_head_tit a27_box"><span class="f_ico">4F</span><a class="f_tit" href="/zx/" target="_blank">美国本科转学</a></div>
			<div class="type_floors_head_tabs">
				<a href="/lxzt/lxsq/" target="_blank">转学专题</a><a class="a_kefu" target="_blank">在线咨询</a><a href="/pinggu/" target="_blank">留学评估</a>
			</div>	
		</div>
<!--type_floors04_left-->
		<div class="type_floors_left">
			<div class="type_floors_left_box mr10 type_floors_left_bannerbox">
				<script type="text/javascript">BAIDU_CLB_fillSlot("1103037");</script>
			</div>
			<div class="type_floors_left_box bt_blue mr10">
				<a class="type_floors_left_box_tit tit_blue" href="/zx/zx/" target="_blank">资讯动态</a>
				<ul class="type_floors_left_box_list">
<li><a href="/zx/zx/21456.html" target="_blank" title="美国社区大学转学成功率汇总"><strong>美国社区大学转学成功率汇</strong></a></li>
<li><a href="/zx/zx/21431.html" target="_blank" title="美国留学不能不知的美国医疗保险常识！"><strong>美国留学不能不知的美国医</strong></a></li>
<li><a href="/zx/zx/21345.html" target="_blank" title="剑走偏锋GPA1.889学生成功逆袭转学到奥本！"><strong>剑走偏锋GPA1.889学生成功逆</strong></a></li>
<li><a href="/zx/zx/21306.html" target="_blank" title="这十类学生可以考虑转学去美国"><strong>这十类学生可以考虑转学去</strong></a></li>
<li><a href="/zx/zx/21227.html" target="_blank" title="转学去全美最大的私立大学--NYU"><strong>转学去全美最大的私立大学</strong></a></li>
<li><a href="/zx/zx/20790.html" target="_blank" title="美国大学必上的六大课程">美国大学必上的六大课程</a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue">
				<a class="type_floors_left_box_tit tit_blue" href="/zx/al/" target="_blank">成功案例</a>
				<ul class="type_floors_left_box_list">
<li><a href="/zx/al/20867.html" target="_blank" title="李琳老师本科转学案例分析七：国内专科续本困难重重，转学去美国">李琳老师本科转学案例分析</a></li>
<li><a href="/zx/al/20868.html" target="_blank" title="李琳老师本科转学案例分析八：走起，转学去西北！">李琳老师本科转学案例分析</a></li>
<li><a href="/zx/al/20869.html" target="_blank" title="李琳老师本科转学案例分析九：有特色的ESSAY让你脱颖而出-密歇根">李琳老师本科转学案例分析</a></li>
<li><a href="/zx/al/20870.html" target="_blank" title="李琳老师本科转学案例分析十：转学的KEY POINTS详解之选校">李琳老师本科转学案例分析</a></li>
<li><a href="/zx/al/20871.html" target="_blank" title="李琳老师本科转学案例分析十一：不抛弃不放弃-拒信变成录取信">李琳老师本科转学案例分析</a></li>
<li><a href="/zx/al/20872.html" target="_blank" title="李琳老师本科转学案例分析十二：从400名到40名的飞跃">李琳老师本科转学案例分析</a></li>

				</ul>
			</div>
			<div class="clear"></div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<div class="border_box bt_none" style="height:99%;">
					<div class="type_right_box_tit">
						<span class="cl_blue tabs4">美国本科转学服务</span>
						<div class="clear"></div>
					</div>
					<ul class="type_floors_left_box_list">
<li><a href="/zhuanti/iplanning/">精英计划</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/zhuanti/guihua/" target="_blank">学习规划</a></li>
							<li><a href="/zhuanti/huodong/" target="_blank">美国前10/30/50名校个性活动策划</a></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">托福全日制保分封闭训练营</a><br /></li>
							<li><a href="/zhuanti/fengbi/" target="_blank">SAT全日制保分封闭训练营</a><br />
</li>
							<li><a href="/zhuanti/baofenban/" target="_blank">托福保分班</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/zhuanti/baofenban/">SAT保分班</a></li>
				  </ul>
				</div>
			</div>
			<div class="type_floors_left_box bt_blue mr10 mt10">
				<a class="type_floors_left_box_tit tit_blue" href="/zx/msfx/" target="_blank">名师经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/zx/msfx/12545.html" target="_blank" title="美国住宿私立高中考取哈耶普斯排名">美国住宿私立高中考取哈耶</a></li>
<li><a href="/zx/msfx/12547.html" target="_blank" title="申请美国本科 交换生有哪些优势">申请美国本科 交换生有哪些</a></li>
<li><a href="/zx/msfx/12564.html" target="_blank" title="美国高中入学面试问题总汇">美国高中入学面试问题总汇</a></li>
<li><a href="/zx/msfx/12563.html" target="_blank" title="美国高中假期时间汇总">美国高中假期时间汇总</a></li>
<li><a href="/zx/msfx/12871.html" target="_blank" title="美国高中交换生的经历和感受">美国高中交换生的经历和感</a></li>
<li><a href="/zx/msfx/17089.html" target="_blank" title="美国名校申请竞争加剧 高二学生如何准备?">美国名校申请竞争加剧 高二</a></li>

				</ul>
			</div>
			<div class="type_floors_left_box bt_blue mt10 ">
				<a class="type_floors_left_box_tit tit_blue" href="/zx/xyfx/" target="_blank">学员经验</a>
				<ul class="type_floors_left_box_list">
<li><a href="/zx/xyfx/12836.html" target="_blank" title="【海外生活】哈佛图书馆墙上的训言">【海外生活】哈佛图书馆墙</a></li>
<li><a href="/zx/xyfx/2558.html" target="_blank" title="海南省第一封录取通知书获得者 弃北大赴美国留学">海南省第一封录取通知书获</a></li>
<li><a href="/zx/xyfx/2568.html" target="_blank" title="出国留学如何保资金安全？">出国留学如何保资金安全？</a></li>
<li><a href="/zx/xyfx/2808.html" target="_blank" title="美国留学热潮下的注意事项">美国留学热潮下的注意事项</a></li>
<li><a href="/zx/xyfx/2916.html" target="_blank" title="留学理财：出国留学贷款办理中常见五问题">留学理财：出国留学贷款办</a></li>
<li><a href="/zx/xyfx/3184.html" target="_blank" title="美国高等教育的印象和思考：宽进严出与玩命学习">美国高等教育的印象和思考</a></li>

				</ul>
			</div>
			<div class="type_floors_left_adbox mt10">
				<ul>
					<li style="display:inline;float:left;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103039");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103040");</script></li>
					<li style="display:inline;float:left;margin-left:10px;"><script type="text/javascript">BAIDU_CLB_fillSlot("1103041");</script></li>
				</ul>
			</div>
			<div class="clear"></div>
		</div>
<!--type_floors04_right-->
		<div class="type_floors_right">
			<div class="type_floors_right_first bt_blue">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/school/university/" target="_blank">大学排行</a><a class="tabs_more" href="/school/university/" target="_blank">更多</a>
					</div>
				  <div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/school/university/St-Michael's-College.html" target="_blank" title="圣迈克尔学院/St.Michael's College">圣迈克尔学院/St.Michael's Col</a></li>
<li><a href="/school/university/Cornell-College.html" target="_blank" title="康奈尔学院/Cornell College">康奈尔学院/Cornell College</a></li>
<li><a href="/school/university/Saint-Mary's-College.html" target="_blank" title="圣玛丽学院/Saint Mary's College">圣玛丽学院/Saint Mary's Colleg</a></li>
<li><a href="/school/university/Berea-College.html" target="_blank" title="伯利亚学院/Berea College">伯利亚学院/Berea College</a></li>
<li><a href="/school/university/Soka-University-of-America.html" target="_blank" title="美国创价大学/Soka University of America">美国创价大学/Soka University </a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_first bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/zx/zhinan/" target="_blank">留学指南</a><a class="tabs_more" href="/zx/zhinan/" target="_blank">更多</a>
					</div>
					<div class="type_right_box_content2">
						<ul class="type_right_box_list">
	<li><a href="/zx/zhinan/21358.html" target="_blank" title="美国本科转学与新生申请的区别"><strong>美国本科转学与新生申请的区</strong></a></li>
<li><a href="/zx/zhinan/21213.html" target="_blank" title="中国学生从失败到逆袭的转折点">中国学生从失败到逆袭的转折</a></li>
<li><a href="/zx/zhinan/20855.html" target="_blank" title="转学申请者选专业，要看综合排名or专业排名？">转学申请者选专业，要看综合排名or专业</a></li>
<li><a href="/zx/zhinan/20791.html" target="_blank" title="细数美国本科转学的三种方式">细数美国本科转学的三种方式</a></li>
<li><a href="/zx/zhinan/20780.html" target="_blank" title="转学美国可申请的五类奖学金">转学美国可申请的五类奖学金</a></li>

						</ul>
					</div>
				</div>
			</div>
			<div class="type_floors_right_second bt_blue mt10">
				<div class="border_box bt_none">
					<div class="type_right_box_tit">
						<a class="tabs2" href="/gre/GREziliao/" target="_blank">GRE资料下载</a><a class="tabs_more" href="/gre/GREziliao/" target="_blank">更多</a>
					</div>
						<ul class="type_right_box_list">
	<li><a href="/gre/GREziliao/19237.html" target="_blank" title="猴哥GRE填空词频蓝宝书下载">猴哥GRE填空词频蓝宝书下载</a></li>
<li><a href="/gre/GREziliao/19236.html" target="_blank" title="GRE数学猴哥独家资料下载">GRE数学猴哥独家资料下载</a></li>
<li><a href="/gre/GREziliao/20344.html" target="_blank" title="记忆GRE词汇的三个步骤">记忆GRE词汇的三个步骤</a></li>
<li><a href="/gre/GREziliao/12779.html" target="_blank" title="[GRE资料] 史上最全的GRE资料下载">[GRE资料] 史上最全的GRE资料下</a></li>

						</ul>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
<!--type_floor_mingshi-->
	<div class="type_floors mt20">
		<div class="type_floors_head bb_black">
			<div class="type_floors_head_tit a27_box"><span class="f_tit" >名师介绍</span></div><a class="tabs_more2" href="/plus/list.php?tid=267" target="_blank">更多</a>
			<div class="clear"></div>	
		</div>
		<div class="type_floors_mingshi mt20" id="scroll_teacher">
			<span class="type_floors_mingshi_l prev"></span>
			<div class="type_floors_mingshi_box box">
				<ul class="type_floors_mingshi_list list">
<li><a href="/ms/20349.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150527/36214-15052G142260-L.png">
						</div>
						<p><span class="name">陈起永</span>服务经验：资深<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20407.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/150529/36214-15052913412BL.png">
						</div>
						<p><span class="name">LIoyd Peterson</span>服务经验：资深<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/21138.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/151022/36228-1510221G100P2.png">
						</div>
						<p><span class="name"> Willie Dixon</span>服务经验：资深<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20361.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150527/36214-15052G513230-L.png">
						</div>
						<p><span class="name">秦老师</span>服务经验：10年<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20721.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/150724/36220-150H41636312O.png">
						</div>
						<p><span class="name">孙老师</span>服务经验：5年<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20457.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150608/36214-15060P94K00-L.png">
						</div>
						<p><span class="name">Alan</span>服务经验：3年<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20351.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150527/36214-15052G316050-L.png">
						</div>
						<p><span class="name">文老师</span>服务经验：6年<br/>服务地区：北京<br/>级别：VIP留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20352.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150527/36214-15052G31S30-L.png">
						</div>
						<p><span class="name">鲁老师</span>服务经验：9年<br/>服务地区：北京<br/>级别：红钻留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20453.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150608/36214-15060PUT10-L.png">
						</div>
						<p><span class="name">徐老师</span>服务经验：7年<br/>服务地区：北京<br/>级别：红钻留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20104.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/150520/36214-150520143RV24.png">
						</div>
						<p><span class="name">扈老师</span>服务经验：8年<br/>服务地区：上海<br/>级别：红钻留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20113.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150521/36214-1505211106160-L.png">
						</div>
						<p><span class="name">孙老师</span>服务经验：5年<br/>服务地区：北京<br/>级别：钻石留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li><li><a href="/ms/20354.html" target="_blank">
						<div class="pic">
							<img class="teacher_bg" src="/templets/style/images/teacher_yuan.png">
							<img class="teacher" src="/uploads/allimg/150527/36214-15052G452000-L.png">
						</div>
						<p><span class="name">姜老师</span>服务经验：多年<br/>服务地区：北京<br/>级别：钻石留学申请顾问</p></a>
                    <a class="a_kefu anniu1">立即咨询</a>
                    <a class="a_kefu anniu2">在线预约</a>
					</li> 
				</ul>
			</div>
			<span class="type_floors_mingshi_r next"></span>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
<script>
//滑动效果
$('#scroll_teacher').cxScroll({
	direction: 'left',
	step: 2,
	auto:false,
	accel:500
});
</script>
</div>
<style type="text/css">
/*!common/css/init.css*/
body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,button,textarea,select,p,blockquote,th,td{margin:0;padding:0;} 
body{color:#000;background:#fff;} 
table{border-collapse:collapse;border-spacing:0;} 
caption,th{text-align:left;} 
fieldset,img{border:0;} 
abbr,acronym{border:0;font-variant: normal;} 
:focus{outline:0;} 
input,select{height:20px;font-size:12px;line-height:20px;} 
del,ins{text-decoration:none;} 
ol,ul,dl{list-style:none;} 
h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;} 
a,a:link,a:visited,a:active{text-decoration:none;} 
a:hover{text-decoration:underline;} 

/*** 页面重置初始化样式开始 ***/


/*** 基础公共样式开始***/

/** 定位公共样式 **/
.clear{clear:both;}
.fc:after{content:".";display:block;height:0;clear:both;visibility:hidden;}
.fc{display:inline-block;*zoom:1;}
/* Hides from IE-mac */
* html .fc{height:1%;}
.fc{display:block;}
/* End hide from IE-mac */
.fl{float:left;}
.fr{float:right;}
.pos_a{position:absolute;}
.pos_r{position:relative;}
.pos_f{position:fixed;}


/** 盒子公共样式 **/
/* 宽高样式 */
.w1000{width:1000px;margin-left:auto;margin-right:auto;}/**主体外框**/
.w1200{width:1200px;margin-left:auto;margin-right:auto;}/**主体外框**/
.w100{width:190px;}
.w200{width:200px;}
.w260{width:260px;}
.w378{width:378px;}
.w260{width:260px;}
.w736{width:736px;}
.h100{height:100px;}
.h200{height:200px;}
/* 外边距样式 */
.mt1{margin-top:1px;}
.mt5{margin-top:5px;}
.mt10{margin-top:10px;}
.mt15{margin-top:15px;}
.mt20{margin-top:20px;}
.mt30{margin-top:30px;}
.mt32{margin-top:32px;}
.mr5{margin-right:5px;}
.mr10{margin-right:10px;}
.mr15{margin-right:15px;}
.mb5{margin-bottom:5px;}
.mb10{margin-bottom:10px;}
.mb15{margin-bottom:15px;}
.mb20{margin-bottom:20px;}
.ml1{margin-left:1px;}
.ml5{margin-left:5px;}
.ml10{margin-left:10px;}
.ml17{margin-left:17px;}
.ml20{margin-left:20px;}
.ml32{margin-left:32px;}
.ml35{margin-left:35px;}
.ml15{margin-left:15px;}
.ml40{margin-left:40px;}
/* 内边距样式 */
.pt5{padding-top:5px;}
.pt10{padding-top:10px;}
.pt15{padding-top:15px;}
.pr5{padding-right:5px;}
.pr10{padding-right:10px;}
.pr15{padding-right:15px;}
.pb5{padding-bottom:5px;}
.pb10{padding-bottom:10px;}
.pb15{padding-bottom:15px;}
.pl5{padding-left:5px;}
.pl10{padding-left:10px;}
.pl15{padding-left:15px;}
/* 背景样式 */
.bg_white{color:#ffffff;}
.bg_black{color:#fff;}
.bg_grey{color:#ccc;}
.bg_blue{color:#0000ff;}
.bg_red{color:#ff0000;}
.bg_green{color:#006600;}
.bg_yellow{color:#ff6600;}
/* 三角形 */
.trans_t10{width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:20px solid red;}/* 角向上的三角形 */
.trans_b10{width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-top:20px solid red;}/* 角向下的三角形 */
.trans_l10{width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:20px solid red;}/* 角向左的三角形 */
.trans_r10{width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:20px solid red;}/* 角向右的三角形 */

/** 字体公共样式 **/
/* 字体组合 */
.ft12{font:normal 12px "Microsoft YaHei";}
.ft13{font:normal 13px "Microsoft YaHei";}
.ft14{font:normal 14px "Microsoft YaHei";}
.ft15{font:normal 15px "Microsoft YaHei";}
.ft16{font:normal 16px "Microsoft YaHei";}
.ft18{font:normal 18px "Microsoft YaHei";}
.ft20{font:normal 20px "Microsoft YaHei";}
.ft22{font:normal 22px "Microsoft YaHei";}
.ft24{font:normal 24px "Microsoft YaHei";}
.ft36{font:normal 36px "Microsoft YaHei";}
/* 加粗 */
.fwb{font-weight:bold;}
.fwn{font-weight:normal;}
/* 斜体 */
.fsn{font-style:normal;}
.fso{font-style:oblique;}
/* 大小 */
.fs12{font-size:12px;}
.fs14{font-size:14px;}
.fs16{font-size:16px;}
.fs18{font-size:18px;}
.fs20{font-size:20px;}
.fs24{font-size:24px;}
.fs36{font-size:36px;}
/* 行高 */
.lh26{line-height:26px;}
.lh30{line-height:30px;}
.lh40{line-height:30px;}
/* 字体 */
.ffyh{font-family:"Microsoft YaHei";}
.ffss{font-family:"SimSun";}
/* 对齐方式 */
.tac{text-align:center;}
.tal{text-align:left;}
.tar{text-align:right;}
/* 字体颜色 */
.fc_white{color:#ffffff;}
.fc_black{color:#fff;}
.fc_grey{color:#797979;}
.fc_blue{color:#0000ff;}
.fc_red{color:#ff0000;}
.fc_green{color:#006600;}
.fc_yellow{color:#ff6600;}
/* 省略号 */
.omit{display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;_text-overflow:clip;}
/* 强制换行 */
.wbw_b{word-break:break-all; /*支持IE，chrome，FF不支持*/word-wrap:break-word;/*支持IE，chrome，FF*