<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",10418,10458);
$z[4][4]['filename']="nyheader.htm";
$z[5]=Array("field","",10812,10841);
$z[5][4]['name']="position";
$z[6]=Array("field","",10936,10955);
$z[6][4]['name']="title";
$z[7]=Array("field","",11072,11128);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",11220,11245);
$z[8][4]['name']="description";
$z[9]=Array("field","",11358,11376);
$z[9][4]['name']="body";
$z[10]=Array("prenext","",12039,12064);
$z[10][4]['get']="pre";
$z[11]=Array("prenext","",12089,12115);
$z[11][4]['get']="next";
$z[12]=Array("arclist","  \r\n      <li><span><a href=\"[field:arcurl/]\" target=\"_blank\">[[field:typename /]]</a></span><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"><strong>[field:title/]</strong></a></li>\r\n ",13487,13730);
$z[12][4]['row']="10";
$z[13]=Array("include","",14302,14343);
$z[13][4]['filename']="cgalright.htm";
$z[14]=Array("include","",20949,20985);
$z[14][4]['filename']="tjzx.htm";
$z[15]=Array("include","",24362,24400);
$z[15][4]['filename']="footer.htm";

?>