<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",9800,9840);
$z[4][4]['filename']="nyheader.htm";
$z[5]=Array("field","",10096,10125);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n<li>\r\n				<a class=\"p_l bg_blue\" href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a>\r\n				<div class=\"p_r\">\r\n					<a class=\"tit \" href=\"[field:arcurl/]\" target=\"_blank\" >[field:title/]</a>\r\n					<p>[field:description function=\"cn_substr(@me,150)\" /]...</p>\r\n				</div>\r\n				<div class=\"clear\"></div>\r\n			</li>\r\n            \r\n    ",11474,11866);
$z[6][4]['pagesize']="5";
$z[6][4]['titlelen']="34";
$z[7]=Array("pagelist","",11903,11974);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",11997,12038);
$z[8][4]['filename']="cgalright.htm";
$z[9]=Array("include","",18505,18541);
$z[9][4]['filename']="tjzx.htm";
$z[10]=Array("include","",21918,21956);
$z[10][4]['filename']="footer.htm";

?>