<li>      				
                            <h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
                            <p>[field:description/]...</p>
                            <span>
                                <a href="[field:arcurl/]">[field:global.cfg_basehost/][field:arcurl/]</a>
                                <small>ÈÕÆÚ£º</small>[field:stime/]
                            </span>
                        </li>