<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:fwjy itemname="服务经验" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fwjy>

<field:fwdq itemname="服务地区" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fwdq>

<field:fwjb itemname="服务级别" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fwjb>

<field:fwjd itemname="服务阶段" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fwjd>

<field:shipin itemname="留学视频" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shipin>

<field:mslb itemname="名师类别" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="咨询顾问,留学申请顾问,满分名师,活动规划师,科研实习规划TUTOR"  maxlength="250" page="">
</field:mslb>

<field:msdq itemname="名师地区" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="北京,上海,广州,深圳,沈阳,武汉,西安,南京,郑州,贵阳,太原,大连,厦门,成都,昆明"  maxlength="250" page="">
</field:msdq>
<field:mshg itemname="名师海归" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="否,是"  maxlength="250" page="">
</field:mshg>
<field:fwgy itemname="服务感言" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fwgy>
<field:cgal itemname="成功案例" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:cgal>

<field:haigui itemname="是否海归" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:haigui>
