<li> <a href="[field:arcurl/]" target="_blank" class="teachers_list_one 0">
        <div class="teachers_list_one_box">
          <div class="teachers_list_one_box_top"><img src="/templets/style/images/teacher_tags/vip.png"></div>
          <div class="clear"></div>
          <div class="teachers_list_one_box_pic"><img class="teacher_p" src="[field:litpic/]"><img class="teacher_bg" src="/templets/style/images/teacher_bg.png"></div>
          
          <div class="teachers_list_one_box_text"> <span class="name a27_box">[field:title/]</span> <span class="jingyan a27_box">服务经验：[field:fwjy/]</span> <span class="diqu a27_box">服务地区：[field:fwdq/]</span> <span class="jibie a27_box">服务级别：[field:fwjb/]</span><span class="jingyan a27_box">服务阶段：[field:fwjd/]</span> <span class="jianjie">[field:description function="cn_substr(@me,80)" /]...</span> </div>
        </div>
        </a>
        <div class="clear"></div>      
        <div class="teachers_list_one_tags"> <span><img src="/templets/style/images/teacher_tags/vip.png" title="VIP级名师"></span><span><img src="/templets/style/images/teacher_tags/haigui.png" title="海归背景"></span>
          <div class="clear"></div>
        </div>
      </li>