<?php
$z[0]=Array("include","",9812,9852);
$z[0][4]['filename']="nyheader.htm";
$z[1]=Array("include","",9953,9991);
$z[1][4]['filename']="nyleft.htm";
$z[2]=Array("field","",10254,10273);
$z[2][4]['name']="title";
$z[3]=Array("field","",10298,10316);
$z[3][4]['name']="body";
$z[4]=Array("include","",16803,16839);
$z[4][4]['filename']="tjzx.htm";
$z[5]=Array("include","",20220,20258);
$z[5][4]['filename']="footer.htm";

?>