<?php
$z[0]=Array("include","",9851,9891);
$z[0][4]['filename']="nyheader.htm";
$z[1]=Array("include","",9995,10033);
$z[1][4]['filename']="nyleft.htm";
$z[2]=Array("list","\r\n          <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><span>[field:stime/]</span><div class=\"clear\"></div></li>\r\n        ",10182,10377);
$z[2][4]['pagesize']="10";
$z[2][4]['titlelen']="34";
$z[3]=Array("pagelist","",10425,10496);
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[3][4]['listsize']="3";
$z[4]=Array("include","",16982,17018);
$z[4][4]['filename']="tjzx.htm";
$z[5]=Array("include","",20397,20435);
$z[5][4]['filename']="footer.htm";

?>