<?php
$z[0]=Array("global","",110,136);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",180,210);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",247,274);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1522,1560);
$z[3][4]['filename']="header.htm";
$z[4]=Array("arclist","\r\n				                <a href=\"[field:arcurl/]\">[field:title/]<em class=\"in_bx1_r_ico1\"></em></a>\r\n",18804,18968);
$z[4][4]['typeid']="12";
$z[4][4]['row']="4";
$z[4][4]['titlelen']="30";
$z[5]=Array("arclist","\r\n				<li class=\"fc\"><em class=\"in_bx1_l_time\">[field:stime/]</em><strong>…Ó€⁄</strong><a href=\"[field:arcurl/]\"target=\"_blank\">[field:title/]</a><em class=\"in_bx1_r_ico2\"></em><em class=\"in_bx1_yyico\"><a class=\"a_kefu\" href=\"javascript:;\" rel=\"nofollow\" target=\"_self\" style=\"cursor: pointer\">‘§‘º</a></em></li>\r\n                ",21840,22236);
$z[5][4]['typeid']="142";
$z[5][4]['row']="8";
$z[5][4]['titlelen']="30";
$z[6]=Array("arclist","\r\n				<li class=\"fc\"><a href=\"[field:arcurl/]\" >[field:title/]</a><em class=\"in_bx1_r_ico1\"></em><em class=\"in_bx1_yyico\"><a href=\"[field:arcurl/]\">œÍ«È</a></em></li>\r\n                  ",22336,22592);
$z[6][4]['typeid']="115,118";
$z[6][4]['row']="8";
$z[6][4]['titlelen']="40";
$z[7]=Array("include","",129291,129327);
$z[7][4]['filename']="tjzx.htm";
$z[8]=Array("include","",130349,130387);
$z[8][4]['filename']="footer.htm";

?>