<?php
$z[0]=Array("include","",9813,9853);
$z[0][4]['filename']="nyheader.htm";
$z[1]=Array("field","",10625,10654);
$z[1][4]['name']="position";
$z[2]=Array("field","",10706,10735);
$z[2][4]['name']="typename";
$z[3]=Array("list","\r\n<li><a class=\"list_l_content_type\" href=\"[field:arcurl/]\" target=\"_blank\">[[field:typename /]]</a><a href=\"[field:arcurl/]\" target=\"_blank\"><b>[field:title/]</b></a><span>[field:stime/]</span><div class=\"clear\"></div></li>\r\n",10830,11108);
$z[3][4]['pagesize']="42";
$z[3][4]['titlelen']="34";
$z[4]=Array("pagelist","",11155,11226);
$z[4][4]['listitem']="info,index,end,pre,next,pageno";
$z[4][4]['listsize']="3";
$z[5]=Array("include","",11508,11549);
$z[5][4]['filename']="cgalright.htm";
$z[6]=Array("include","",18016,18052);
$z[6][4]['filename']="tjzx.htm";
$z[7]=Array("include","",21430,21468);
$z[7][4]['filename']="footer.htm";

?>