<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",9938,9978);
$z[4][4]['filename']="nyheader.htm";
$z[5]=Array("include","",31165,31201);
$z[5][4]['filename']="tjzx.htm";
$z[6]=Array("include","",34579,34617);
$z[6][4]['filename']="footer.htm";

?>