<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",9862,9902);
$z[4][4]['filename']="nyheader.htm";
$z[5]=Array("list"," \r\n<li><a class=\"list_l_content_type\" href=\"[field:arcurl/]\" target=\"_blank\">[[field:typename /]]</a><a href=\"[field:arcurl/]\">[field:title/]</a><span>[field:stime/]</span><div class=\"clear\"></div></li>\r\n",10243,10472);
$z[6]=Array("pagelist","",10519,10590);
$z[6][4]['listitem']="info,index,end,pre,next,pageno";
$z[6][4]['listsize']="3";
$z[7]=Array("include","",10902,10943);
$z[7][4]['filename']="cgalright.htm";
$z[8]=Array("include","",17425,17461);
$z[8][4]['filename']="tjzx.htm";
$z[9]=Array("include","",20838,20876);
$z[9][4]['filename']="footer.htm";

?>